### PR TITLE
dynamic index

### PR DESCRIPTION
**Pull request by abbbi**
my attempt to support dynamic index:

what works:

1) backup with proxmox-backup-client
2) listing snapshots using proxmox-backup-client (no sizes reported, ..)
3) dump the archive using proxmox-backup-client
4) restore via proxmox-backup-client
5) mounting archives

Update: the issues with restore were due to me executing proxmox-backup-client w/o root access and the backup contained files only root had access too.

So as it stands everything seems to work correctly.

### CODE REVIEW

**Comment by abbbi** [comment]
Seems there might be a race condition still, happens if backing up lots of data wihch is new.
The map where original digest sizes are stored might be better beeing a Sync.map,too.

```
fatal error: concurrent map writes

goroutine 12098 [running]:
main.(*Server).ServeHTTP(0xc0000aa090, {0x9663d8, 0xc0000d2000}, 0xc00039a120)
|   /home/abi/pmoxs3backuproxy/cmd/pmoxs3backuproxy/main.go:615 +0x2d7a
golang.org/x/net/http2.(*serverConn).runHandler(0x444c3d?, 0x0?, 0x0?, 0xc00006afb8?)
|   /home/abi/go/pkg/mod/golang.org/x/net@v0.26.0/http2/server.go:2414 +0x113
created by golang.org/x/net/http2.(*serverConn).scheduleHandler in goroutine 6
|   /home/abi/go/pkg/mod/golang.org/x/net@v0.26.0/http2/server.go:2348 +0x21d

```

**Comment by abbbi** [comment]
occasionally this one is seen after introducing sync.map:

Error: wrong size for file 'root.pxar.didx' (14607286 != 2694231)

not sure whats going on.

**Comment by tizbac** [comment]
Really awesome work, thanks 
The change you did on garbage collector tho is wrong
GC process MUST not continue if an unsupported format is encountered because it will not mark used chunks and mistakenly delete them

**Comment by abbbi** [comment]
oh dear, reverted.

**Comment by abbbi** [comment]
added an basic functionality test using github actions

**Pull request merged**
